#! /bin/sh

#autostart
pgrep -x sxhkd > /dev/null || sxhkd &
~/.fehbg &
light-locker --lock-on-suspend --lock-on-lid &
#polybar -c /home/widward/.config/polybar/config

#monitors
bspc monitor eDP-1 -d 1 2 3 4 5
#bspc monitor HDMI-0 -d 6 7 8 9 0

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#global settings
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config focused_border_color "#00e5a8"

polybar -c /home/widward/.config/polybar/config
